version: '3'
services:
  app:
    build: .
    # env_file:
    #   - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "DATABASE_URL=postgres://postgres:mypassword@db:5432/bank npm run migrate up &&
             npm run dev"
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
  
  db:
    image: postgres:14-alpine
    # env_file:
    #   - ./.env
    volumes:
      - dev-db-bank:/var/lib/postgres
    ports:
      - "5432:5433"
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_PASSWORD=mypassword

volumes:
  dev-db-bank: